<?php

namespace Clement\BlogBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
   /* public function findByArticle($id){
        $qp = $this->createQueryBuilder('c')
            ->where('c.article_id = '.$id);

        return $qp->getQuery()->getArrayResult();
    }*/

    public function findAllByArray($titre = null){
        $qp = $this->createQueryBuilder('a');

        if($titre != null){
            $qp->where('a.titre LIKE :search');
            $qp->setParameter('search', '%'.$titre.'%');
        }

        return $qp->getQuery()->getArrayResult();
    }
}
